\input texinfo
@setfilename doc.info
@documentencoding UTF-8

@settitle 3DViewer

@copying
Copyright © 2023 Bizarrol Annemari Birdpers
@end copying


@titlepage
@title 3DViewer
@insertcopying
@end titlepage

@contents

@node 3DViewer
@chapter 3DViewer

@cindex intro
Вывод 3д моделей в каркасном виде используя афинные преобразования.

@node создание gif
@chapter создание gif

@cindex intro
Приложение позволят записать gif изображение вращения и изменения модели, запись происходит в 10fps и длится 5 секунд.

@node создание скриншотов
@chapter создание скриншотов

@cindex intro
Приложение позволяет создавать снимки модели в форматах jpeg и bmp.

@node изменение вершин
@chapter изменение вершин

@cindex intro
пользоваетель может выбрать любой цвет для отображения вершин, 
а так же предоставлен выбор между круглыми вершинами, квадратными и их отсутсвием.
Размер вершин так же является изменяемым

@node изменение граней
@chapter изменение граней

@cindex intro
пользоваетель может выбрать любой цвет для отображения граней, 
а так же предоставлен выбор между целыми гранями, пунктирными и их отсутсвием.
Размер граней так же является изменяемым

@node изменение фона
@chapter изменение фона

@cindex intro
пользоваетель может менять фон на любой цвет.

@node перемещение модели
@chapter перемещение модели

@cindex intro
пользоваетель имеет возможность перемещать модель, вращать и изменять масштаб модели.

@node проекция
@chapter проекция

@cindex intro
пользователь может изменить проекцию с параллельной на центральную и наоборот.
